% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={hw04},
  pdfauthor={Michael Puchalski},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{hw04}
\author{Michael Puchalski}
\date{2025-02-10}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse,LaTeX)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.1.4     v readr     2.1.5
## v forcats   1.0.0     v stringr   1.5.1
## v ggplot2   3.5.1     v tibble    3.2.1
## v lubridate 1.9.3     v tidyr     1.3.1
## v purrr     1.0.2     
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df}\OtherTok{\textless{}{-}}\FunctionTok{read.table}\NormalTok{(}\StringTok{"copier.txt"}\NormalTok{, }\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\section{1. (R required) We will use the dataset ``Copier.txt'' for this
question. The Tri-City Office Equipment Corporation sells an imported
copier on a franchise basis and performs preventive maintenance and
repair service on this copier. The data have been collected from 45
recent calls on users to perform routine preventive maintenance service;
for each call, Serviced is the number of copiers serviced and Minutes is
the total number of minutes spent by the service
person.}\label{r-required-we-will-use-the-dataset-copier.txt-for-this-question.-the-tri-city-office-equipment-corporation-sells-an-imported-copier-on-a-franchise-basis-and-performs-preventive-maintenance-and-repair-service-on-this-copier.-the-data-have-been-collected-from-45-recent-calls-on-users-to-perform-routine-preventive-maintenance-service-for-each-call-serviced-is-the-number-of-copiers-serviced-and-minutes-is-the-total-number-of-minutes-spent-by-the-service-person.}

\subsection{(a) What is the response variable in this analysis? What is
predictor in this
analysis?}\label{a-what-is-the-response-variable-in-this-analysis-what-is-predictor-in-this-analysis}

In this analysis the response variable is ``minutes'', as in the total
number of minutes spent by the service person. The predictor is
``Serviced'', the total number of copiers serviced. \#\# (b) Produce a
scatterplot of the two variables. How would you describe the
relationship between the number of copiers serviced and the time spent
by the service person?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Serviced, }\AttributeTok{y =}\NormalTok{ Minutes))}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw04Q1_files/figure-latex/unnamed-chunk-2-1.pdf} I
would describe this, at least qualitatively, as a positive linear
relationship between copiers serviced and the time spent doing so. \#\#
(c) What is the correlation between the total time spent by the service
person and the number of copiers serviced? Interpret this correlation
contextually. As mentioned above, this correlates as a positive linear
relationshp. This means that the more opiers there are to be serviced,
the more total time that there will be spent on servicing the copiers.
\#\# (d) Can the correlation found in part 1c be interpreted reliably?
Briefly explain. It can be interpreted yes, but to do so reliabley, a
linear model needs to be applied to it in order to ensure that any
interpretations made are done so with minimal human bias \#\# (e) Use
the lm() function to fit a linear regression for the two variables.
Where are the values of βˆ 1, βˆ 0, R2 , and ˆσ 2 for this linear
regression?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm\_result}\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Minutes}\SpecialCharTok{\textasciitilde{}}\NormalTok{Serviced, }\AttributeTok{data =}\NormalTok{ df)}
\FunctionTok{summary}\NormalTok{(lm\_result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Minutes ~ Serviced, data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -22.7723  -3.7371   0.3334   6.3334  15.4039 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  -0.5802     2.8039  -0.207    0.837    
## Serviced     15.0352     0.4831  31.123   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 8.914 on 43 degrees of freedom
## Multiple R-squared:  0.9575, Adjusted R-squared:  0.9565 
## F-statistic: 968.7 on 1 and 43 DF,  p-value: < 2.2e-16
\end{verbatim}

B1 = 15.0352, B0 = -0.5802, R squared = 0.9575, sigma squared
-\textgreater{} variance = 79.4594 B1 comes from the Serviced Estimate,
B2 comes from the Intercept Estimate, R squared is the unadjusted value
from the model. Variance is the Residual standard Error squared. \#\#
(f) Interpret the values of βˆ 1, βˆ 0 contextually. Does the value of
βˆ0 make sense in this context? The B1 value (the slope), describes how
for every 1 machine serviced, there is an expected service time of 15
minutes. The B0 value (the y-intercept), is a negative value, however,
this makes sense because there is no service time when there is no
machine to be serviced. \#\# (g) Use the anova() function to produce the
ANOVA table for this linear regression. What is the value of the ANOVA F
statistic? What null and alternative hypotheses are being tested here?
What is a relevant conclusion based on this ANOVA F statistic?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(lm\_result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: Minutes
##           Df Sum Sq Mean Sq F value    Pr(>F)    
## Serviced   1  76960   76960  968.66 < 2.2e-16 ***
## Residuals 43   3416      79                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

The F statistic here is 968.66. The null hypothesis H0 =0, alternative
ha does not equal 0. The relevant conclusion to be made here is based on
the very high F statistic, the null hypothesis is rejected meaning the
variance is explained more by the model than the error terms.

\end{document}
